title: LoveTruth.life
email: your-email@example.com
description: higher consciousness in a modern world
baseurl: ''
url: ''
markdown: kramdown
plugins:
  - jekyll-feed
destination: /usr/share/nginx/html/
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: pages
    values:
      layout: default
sass:
  style: compressed
